package com.CenterPiece.CenterPiece.TrelloIDs;

public enum TrelloLists {
    QUOTED, BATCHING, DRAWING_RECHECK, PROCESSING, SO_SID_CHECK,
    ON_HOLD, TO_BE_ORDERED, ON_ORDER, TO_BE_RECEIVED_SHOP, RECEIVING, CREDIT_HOLD,
    SCHEDULING_POOL, PRODUCTION_QUEUE, IN_PRODUCTION, RM_TO_BE_COMPLETED_RS,
    TO_BE_PICKED, PICKED_AND_STAGED, TO_BE_LOADED_ROUTED,
    WILL_CALL, TRANSFERRED_TO_NASHVILLE, ON_TRUCK_ON_DELIVERY,
    DELIVERED_PICKED_UP, COD_TO_BE_PAID, INVOICED, RECEIVED, BRANCH_ID, INBOX
}
