package com.CenterPiece.CenterPiece.TrelloIDs;

public enum TrelloLists {
    QUOTED, DRAWING, BATCHING, DRAWING_RECHECK, PROCESSING, SO_JAMES_CHECK, HOLD_FOR_BATCHING, SO_SID_CHECK,
    ON_HOLD, TO_BE_ORDERED, ON_ORDER, TO_BE_RECEIVED_SHOP, RECEIVING, PARTIAL_RECEIPT, CREDIT_HOLD,
    SCHEDULING_POOL, PRODUCTION_QUEUE, IN_PRODUCTION, PICK_REMAINING_ITEMS,
    TO_BE_PICKED, ORDER_IN_STAGING_BIN, ORDER_STAGED, SENT_TO_PICK, TO_BE_LOADED_ROUTED,
    WILL_CALL, TRANSFERRED_TO_NASHVILLE, ON_TRUCK_ON_DELIVERY,
    DELIVERED_PICKED_UP, COD_TO_BE_PAID, INVOICED, RECEIVED, BRANCH_ID, INBOX, CANCELED
}
