package com.CenterPiece.CenterPiece;

public enum TrelloLists {
    QUOTED, BATCHING, PROCESSING, SO_SID_CHECK,
    ON_HOLD, TO_BE_ORDERED, ON_ORDER, RECEIVING,
    SCHEDULING_POOL, PRODUCTION_QUEUE, IN_PRODUCTION,
    TO_BE_PICKED, PICKED_AND_STAGED, TO_BE_LOADED_ROUTED,
    WILL_CALL, ON_TRUCK_ON_DELIVERY, DELIVERED_PICKED_UP,
    INVOICED, RECEIVED, BRANCH_ID, INBOX,
}
