name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-conteiner:
    name: Build container
    runs-on: ubuntu-latest

    steps:     
    - uses: actions/checkout@v4
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build and push to Docker
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: beakston/centerpiece:latest
     
